query getNewsletterInterest(
  $acronym: String
  $fields: [String]
  $where: String
) {
  documents(
    acronym: $acronym
    fields: $fields
    where: $where
  ) @context(provider: "vtex.store-graphql"){
    fields {
      key
      value
    }
  }
}
